### ISSUE TITLE
All highlights cleared, but names remain highlighted at the bottom

### ISSUE THREAD

**Issue by harvanchik** [JRJurman/when2meet-people-highlighter#2]
![image](https://user-images.githubusercontent.com/66141166/224530772-6cc66be6-cd1d-4f4f-bca6-bcbff1ebca49.png)
![image](https://user-images.githubusercontent.com/66141166/224530785-71725231-0cf2-47c7-af58-28d4bbf87eb4.png)

When unselecting a name, all availability is cleared, but the other names still remain selected at the bottom right.

**Comment by JRJurman** [comment]
I'm not seeing this behavior locally - can you give more details about your setup? At a minimum, what browser you are using, and potentially any other extensions you have that might impact CSS.

**Comment by harvanchik** [comment]
[![Image from Gyazo](https://i.gyazo.com/c5c711e4f350e5fcd8f223f72d6d615d.gif)](https://gyazo.com/c5c711e4f350e5fcd8f223f72d6d615d)

I am using Brave Browser, and I don't have any other extensions changing the CSS on the page.

**Comment by JRJurman** [comment]
Oh, I misinterpreted the issue, and am seeing it on my browser as well! I'll try to get a fix together 👍

**Comment by JRJurman** [comment]
Ha, it looks like I left myself a note back when I first wrote this (5 years ago) 

```js
// resetColors function
// resets all the colors back to normal
// Note: can't really do a per-user basis, because highlighting users overlaps
// it would require significant logic, and state management
```

I guess the best quick solution is also un-activate all the other buttons - I've put that together, which isn't the best solution, but it should act in a less unexpected after unselecting a user. 

I've put that up for review, and will close this once that has been published. Of course, this project is open to pull requests if anyone would like to build a more complex solution 😄

**Comment by JRJurman** [comment]
Okay, new version should be deployed, @harvanchik if you can verify, that would be awesome 👍

**Comment by harvanchik** [comment]
Problem solved!  Appreciate the quick response and fix time.
